name: eslint #произвольно выбранное имя задания

on: push  # on – определяет события, которые запускают воркфлоу

jobs:
  
  test:
    # операционная система для работы воркфлоу
    runs-on: ubuntu-latest
    steps: # список шагов, которые надо выполнить
      - name: checkout
        uses: actions/checkout@v2 # checkout – клонирует репозиторий

      - name: install
        run: make install

      - name: linter
        run: make lint
